# Generated by Django 4.2.30 on 2026-05-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='background_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
    ]
