# Generated by Django 4.2.30 on 2026-05-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_background_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
