# Generated by Django 4.2.30 on 2026-05-26 19:20

import cards.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=cards.storage_backends.PDFCloudinaryStorage(), upload_to='card_pdfs/'),
        ),
    ]
