# Generated by Django 4.2.30 on 2026-05-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='message',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
